/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Claim, Payment, Note, AuditLog, Provider, Payer, User, Setting, ClaimStatus, ClaimClassification, ErrorCategory, UserRole, FeeSchedule, EligibilityCoverage, ReportFeeSchedule } from "./types";
import { calculateClaimFinancials } from "./reconciliationEngine";
import { serializeMenuAccess, serializeProviderAccess, ROLE_DEFAULT_MENU_ACCESS } from "./accessControl";

export const SEED_PROVIDERS: Provider[] = [
  { provider_id: "PROV_01", provider_name: "Dr. Robert Chen", npi: "1982736450", practice_id: "PRAC_01", practice_name: "Metropolitan Care Group", active: true },
  { provider_id: "PROV_02", provider_name: "Dr. Sarah Jenkins", npi: "1457382910", practice_id: "PRAC_01", practice_name: "Metropolitan Care Group", active: true },
  { provider_id: "PROV_03", provider_name: "Dr. Marcus Vance", npi: "1092837465", practice_id: "PRAC_02", practice_name: "Vance Family Medicine", active: true },
  { provider_id: "PROV_04", provider_name: "Dr. Elena Rostova", npi: "1827364590", practice_id: "PRAC_03", practice_name: "Summit Neurology & Wellness", active: true },
];

export const SEED_PAYERS: Payer[] = [
  { payer_id: "PAY_01", payer_name: "Medicare Texas (Novitas)", payer_type: "Medicare", active: true },
  { payer_id: "PAY_02", payer_name: "Blue Cross Blue Shield (BCBS)", payer_type: "Commercial", active: true },
  { payer_id: "PAY_03", payer_name: "Aetna Health", payer_type: "Commercial", active: true },
  { payer_id: "PAY_04", payer_name: "UnitedHealthcare (UHC)", payer_type: "Commercial", active: true },
  { payer_id: "PAY_05", payer_name: "Cigna Health", payer_type: "Commercial", active: true },
];

export const SEED_USERS: User[] = [
  { user_id: "USR_01", name: "Manuel David", email: "mdavid@itera.health", role: UserRole.Admin, menu_access: serializeMenuAccess(ROLE_DEFAULT_MENU_ACCESS[UserRole.Admin]), provider_access: serializeProviderAccess([], true), active: true },
  { user_id: "USR_02", name: "Elena Gomez", email: "egomez@itera.health", role: UserRole.BillingManager, menu_access: serializeMenuAccess(ROLE_DEFAULT_MENU_ACCESS[UserRole.BillingManager]), provider_access: serializeProviderAccess([], true), active: true },
  { user_id: "USR_03", name: "James Smith", email: "jsmith@itera.health", role: UserRole.ReconciliationSpecialist, menu_access: serializeMenuAccess(ROLE_DEFAULT_MENU_ACCESS[UserRole.ReconciliationSpecialist]), provider_access: serializeProviderAccess([], true), active: true },
  { user_id: "USR_04", name: "Dr. Robert Chen", email: "rchen@metrocare.com", role: UserRole.ProviderViewer, menu_access: serializeMenuAccess(ROLE_DEFAULT_MENU_ACCESS[UserRole.ProviderViewer]), provider_access: serializeProviderAccess(["PROV_01"], false), active: true },
  { user_id: "USR_05", name: "Alicia Patel", email: "apatel@itera.health", role: UserRole.Auditor, menu_access: serializeMenuAccess(ROLE_DEFAULT_MENU_ACCESS[UserRole.Auditor]), provider_access: serializeProviderAccess([], true), active: true },
];

export const SEED_SETTINGS: Setting[] = [
  { setting_key: "PROVIDER_SHARE_PERCENT", setting_value: "70", description: "Default percentage share paid to the provider (physician)." },
  { setting_key: "ITERA_SHARE_PERCENT", setting_value: "30", description: "Default percentage share kept by ITERA Health for billing and platform management." },
  { setting_key: "PAYMENT_BASIS", setting_value: "COLLECTIONS", description: "Reconciliation basis. COLLECTIONS pays on received cash, BILLED pays on net collectible charges." },
  { setting_key: "GOOGLE_SHEET_INTEGRATION_ACTIVE", setting_value: "false", description: "Whether Google Sheets real-time synchronization is enabled." },
];

export const SEED_FEE_SCHEDULES: FeeSchedule[] = [
  { id: "FSCH-001", cpt_code: "99453", year: 2026, semester1_rate: 19.20, semester2_rate: 19.50, max_per_dos: 1, description: "RPM - Device set-up and patient education" },
  { id: "FSCH-002", cpt_code: "99454", year: 2026, semester1_rate: 62.44, semester2_rate: 63.10, max_per_dos: 1, description: "RPM - Device supply and daily recordings" },
  { id: "FSCH-003", cpt_code: "99457", year: 2026, semester1_rate: 51.04, semester2_rate: 51.80, max_per_dos: 1, description: "RPM - Treatment management services (first 20 min)" },
  { id: "FSCH-004", cpt_code: "99458", year: 2026, semester1_rate: 41.12, semester2_rate: 41.90, max_per_dos: 2, description: "RPM - Treatment management services (additional 20 min)" },
  { id: "FSCH-005", cpt_code: "99490", year: 2026, semester1_rate: 65.20, semester2_rate: 66.00, max_per_dos: 1, description: "CCM - Clinical staff time (first 20 min)" },
  { id: "FSCH-006", cpt_code: "99439", year: 2026, semester1_rate: 48.15, semester2_rate: 48.95, max_per_dos: 2, description: "CCM - Clinical staff time (additional 20 min)" },
  { id: "FSCH-007", cpt_code: "99491", year: 2026, semester1_rate: 85.30, semester2_rate: 86.20, max_per_dos: 1, description: "CCM - Physician or QHP time (first 30 min)" },
  { id: "FSCH-008", cpt_code: "99424", year: 2026, semester1_rate: 73.40, semester2_rate: 74.20, max_per_dos: 1, description: "PINC - Principal Illness Navigation (first 60 min)" }
];

export const SEED_REPORT_FEE_SCHEDULES: ReportFeeSchedule[] = SEED_FEE_SCHEDULES.map(item => ({
  fee_schedule_id: `R-${item.id}`,
  cpt_hcpcs: item.cpt_code,
  cpt_description: item.description,
  service_type: item.description.split(" - ")[0] || "",
  unit_price: item.semester1_rate,
  itera_fee: Number((item.semester1_rate * 0.3).toFixed(2)),
  effective_date: `${item.year}-01-01`,
  active: true
}));

export const SEED_ELIGIBILITY_COVERAGE: EligibilityCoverage[] = [
  {
    coverage_id: "COV-001",
    practice_id: "PRAC_01",
    practice_name: "Metropolitan Care Group",
    service_type: "RPM",
    period: "2026-05",
    total_eligible_patients: 24,
    notes: "Demo denominator for RPM coverage.",
    created_at: "2026-05-01T00:00:00Z",
    updated_at: "2026-05-01T00:00:00Z"
  },
  {
    coverage_id: "COV-002",
    practice_id: "PRAC_01",
    practice_name: "Metropolitan Care Group",
    service_type: "CCM",
    period: "2026-05",
    total_eligible_patients: 18,
    notes: "Demo denominator for CCM coverage.",
    created_at: "2026-05-01T00:00:00Z",
    updated_at: "2026-05-01T00:00:00Z"
  }
];

// Master list of raw claim entries that will be completed by the reconciliationEngine
const rawClaims: Partial<Claim>[] = [
  {
    claim_id: "CLM-2026-001",
    patient_id: "PAT-8812",
    patient_display_name_masked: "Juan Díaz",
    practice_id: "PRAC_01",
    practice_name: "Metropolitan Care Group",
    provider_id: "PROV_01",
    provider_name: "Dr. Robert Chen",
    provider_npi: "1982736450",
    payer_id: "PAY_01",
    payer_name: "Medicare Texas (Novitas)",
    service_type: "RPM",
    cpt_hcpcs: "99453, 99454, 99457",
    modifiers: "",
    units: 1,
    date_of_service_from: "2026-05-01",
    date_of_service_to: "2026-05-31",
    month_of_service: "2026-05",
    billed_by: "ITERA",
    payment_received_by: "ITERA",
    claim_status: ClaimStatus.Paid,
    claim_classification: ClaimClassification.IteraCollected,
    billed_charge: 150.00,
    allowed_amount: 110.00,
    paid_amount: 110.00,
    insurance_adjustment: 40.00,
    denied_amount: 0.00,
    write_off_amount: 0.00,
    uncollectible_amount: 0.00,
    itera_direct_collection: 110.00,
    provider_direct_collection: 0.00,
    payment_to_physician: 77.00, // 70% of 110.00
    era_received: "Yes",
    eob_received: "Yes",
    payment_date: "2026-06-12",
    check_or_eft_number: "EFT-881273",
    carc_code: "",
    rarc_code: "",
    denial_reason: "",
    error_flag: false,
    error_category: "",
    locked: false,
    lock_reason: "",
    correction_status: "",
    resubmission_date: "",
    corrected_claim_reference: "",
    last_note: "Reconciled. Paid in full by Medicare. Paid 70% ($77.00) to physician Chen.",
    created_at: "2026-05-31T18:00:00Z",
    updated_at: "2026-06-12T14:30:00Z",
    updated_by: "egomez@itera.health",
  },
  {
    claim_id: "CLM-2026-002",
    patient_id: "PAT-2091",
    patient_display_name_masked: "María Silva",
    practice_id: "PRAC_01",
    practice_name: "Metropolitan Care Group",
    provider_id: "PROV_01",
    provider_name: "Dr. Robert Chen",
    provider_npi: "1982736450",
    payer_id: "PAY_02",
    payer_name: "Blue Cross Blue Shield (BCBS)",
    service_type: "CCM",
    cpt_hcpcs: "99490, 99439",
    modifiers: "",
    units: 1,
    date_of_service_from: "2026-05-01",
    date_of_service_to: "2026-05-31",
    month_of_service: "2026-05",
    billed_by: "ITERA",
    payment_received_by: "Provider",
    claim_status: ClaimStatus.Paid,
    claim_classification: ClaimClassification.ProviderCollected,
    billed_charge: 120.00,
    allowed_amount: 90.00,
    paid_amount: 90.00,
    insurance_adjustment: 30.00,
    denied_amount: 0.00,
    write_off_amount: 0.00,
    uncollectible_amount: 0.00,
    itera_direct_collection: 0.00,
    provider_direct_collection: 90.00,
    payment_to_physician: 0.00, // Provider collected directly. Under 70% share, Provider owes ITERA $27.00 (30%)
    era_received: "Yes",
    eob_received: "Yes",
    payment_date: "2026-06-15",
    check_or_eft_number: "CHK-992182",
    carc_code: "",
    rarc_code: "",
    denial_reason: "",
    error_flag: false,
    error_category: "",
    locked: false,
    lock_reason: "",
    correction_status: "",
    resubmission_date: "",
    corrected_claim_reference: "",
    last_note: "Paid directly to Provider. Provider owes ITERA 30% share ($27.00). Balance factored in ending AP.",
    created_at: "2026-05-31T18:05:00Z",
    updated_at: "2026-06-15T16:10:00Z",
    updated_by: "jsmith@itera.health",
  },
  {
    claim_id: "CLM-2026-003",
    patient_id: "PAT-3341",
    patient_display_name_masked: "Luis Gutiérrez",
    practice_id: "PRAC_02",
    practice_name: "Vance Family Medicine",
    provider_id: "PROV_03",
    provider_name: "Dr. Marcus Vance",
    provider_npi: "1092837465",
    payer_id: "PAY_03",
    payer_name: "Aetna Health",
    service_type: "APCM",
    cpt_hcpcs: "99457, 99458",
    modifiers: "",
    units: 1,
    date_of_service_from: "2026-05-01",
    date_of_service_to: "2026-05-31",
    month_of_service: "2026-05",
    billed_by: "Provider",
    payment_received_by: "Provider",
    claim_status: ClaimStatus.Paid,
    claim_classification: ClaimClassification.ProviderCollected,
    billed_charge: 140.00,
    allowed_amount: 100.00,
    paid_amount: 100.00,
    insurance_adjustment: 40.00,
    denied_amount: 0.00,
    write_off_amount: 0.00,
    uncollectible_amount: 0.00,
    itera_direct_collection: 0.00,
    provider_direct_collection: 100.00,
    payment_to_physician: 0.00, // Provider billed and collected. Owed ITERA 30% ($30.00).
    era_received: "Yes",
    eob_received: "Yes",
    payment_date: "2026-06-10",
    check_or_eft_number: "EFT-AE7721",
    carc_code: "",
    rarc_code: "",
    denial_reason: "",
    error_flag: false,
    error_category: "",
    locked: false,
    lock_reason: "",
    correction_status: "",
    resubmission_date: "",
    corrected_claim_reference: "",
    last_note: "Provider Billed & Collected. Provider owes ITERA $30.00 platform fee.",
    created_at: "2026-05-31T18:10:00Z",
    updated_at: "2026-06-10T11:00:00Z",
    updated_by: "jsmith@itera.health",
  },
  {
    claim_id: "CLM-2026-004",
    patient_id: "PAT-4019",
    patient_display_name_masked: "Sandra Knight",
    practice_id: "PRAC_02",
    practice_name: "Vance Family Medicine",
    provider_id: "PROV_03",
    provider_name: "Dr. Marcus Vance",
    provider_npi: "1092837465",
    payer_id: "PAY_04",
    payer_name: "UnitedHealthcare (UHC)",
    service_type: "TCM",
    cpt_hcpcs: "99495, 99496",
    modifiers: "",
    units: 1,
    date_of_service_from: "2026-05-02",
    date_of_service_to: "2026-05-02",
    month_of_service: "2026-05",
    billed_by: "Provider",
    payment_received_by: "ITERA",
    claim_status: ClaimStatus.Paid,
    claim_classification: ClaimClassification.IteraCollected,
    billed_charge: 250.00,
    allowed_amount: 200.00,
    paid_amount: 200.00,
    insurance_adjustment: 50.00,
    denied_amount: 0.00,
    write_off_amount: 0.00,
    uncollectible_amount: 0.00,
    itera_direct_collection: 200.00,
    provider_direct_collection: 0.00,
    payment_to_physician: 140.00, // Pays 70% of 200 to Vance.
    era_received: "Yes",
    eob_received: "Yes",
    payment_date: "2026-06-18",
    check_or_eft_number: "EFT-UHC102",
    carc_code: "",
    rarc_code: "",
    denial_reason: "",
    error_flag: false,
    error_category: "",
    locked: false,
    lock_reason: "",
    correction_status: "",
    resubmission_date: "",
    corrected_claim_reference: "",
    last_note: "Provider Billed but ITERA Collected. Reconciled and distributed 70% to Provider Vance.",
    created_at: "2026-05-31T18:15:00Z",
    updated_at: "2026-06-18T10:45:00Z",
    updated_by: "egomez@itera.health",
  },
  {
    claim_id: "CLM-2026-005",
    patient_id: "PAT-9912",
    patient_display_name_masked: "Roberto Benítez",
    practice_id: "PRAC_01",
    practice_name: "Metropolitan Care Group",
    provider_id: "PROV_02",
    provider_name: "Dr. Sarah Jenkins",
    provider_npi: "1457382910",
    payer_id: "PAY_01",
    payer_name: "Medicare Texas (Novitas)",
    service_type: "RPM",
    cpt_hcpcs: "99454, 99457, 99458",
    modifiers: "",
    units: 1,
    date_of_service_from: "2026-05-01",
    date_of_service_to: "2026-05-31",
    month_of_service: "2026-05",
    billed_by: "ITERA",
    payment_received_by: "Split",
    claim_status: ClaimStatus.Paid,
    claim_classification: ClaimClassification.SplitCollection,
    billed_charge: 150.00,
    allowed_amount: 120.00,
    paid_amount: 120.00,
    insurance_adjustment: 30.00,
    denied_amount: 0.00,
    write_off_amount: 0.00,
    uncollectible_amount: 0.00,
    itera_direct_collection: 50.00,
    provider_direct_collection: 70.00, // Co-pay or secondary payer collected by Provider
    payment_to_physician: 14.00, // 70% of 120 total collections is 84. Provider direct-collected 70, so ITERA pays remaining 14.
    era_received: "Yes",
    eob_received: "Yes",
    payment_date: "2026-06-20",
    check_or_eft_number: "SPLIT-M5512",
    carc_code: "",
    rarc_code: "",
    denial_reason: "",
    error_flag: false,
    error_category: "",
    locked: false,
    lock_reason: "",
    correction_status: "",
    resubmission_date: "",
    corrected_claim_reference: "",
    last_note: "Split collection reconciled. Total collections $120. Provider got $70 directly, ITERA paid $14 to complete $84 physician share.",
    created_at: "2026-05-31T18:20:00Z",
    updated_at: "2026-06-20T16:00:00Z",
    updated_by: "egomez@itera.health",
  },
  {
    claim_id: "CLM-2026-006",
    patient_id: "PAT-1182",
    patient_display_name_masked: "Carlos López",
    practice_id: "PRAC_01",
    practice_name: "Metropolitan Care Group",
    provider_id: "PROV_01",
    provider_name: "Dr. Robert Chen",
    provider_npi: "1982736450",
    payer_id: "PAY_05",
    payer_name: "Cigna Health",
    service_type: "BHI",
    cpt_hcpcs: "99484, 99490",
    modifiers: "",
    units: 1,
    date_of_service_from: "2026-05-10",
    date_of_service_to: "2026-05-10",
    month_of_service: "2026-05",
    billed_by: "ITERA",
    payment_received_by: "ITERA",
    claim_status: ClaimStatus.Paid,
    claim_classification: ClaimClassification.MissingERA,
    billed_charge: 100.00,
    allowed_amount: 80.00,
    paid_amount: 80.00,
    insurance_adjustment: 20.00,
    denied_amount: 0.00,
    write_off_amount: 0.00,
    uncollectible_amount: 0.00,
    itera_direct_collection: 80.00,
    provider_direct_collection: 0.00,
    payment_to_physician: 0.00, // On hold because missing ERA
    era_received: "No",
    eob_received: "Yes",
    payment_date: "2026-06-14",
    check_or_eft_number: "CHK-CIG-9912",
    carc_code: "",
    rarc_code: "",
    denial_reason: "",
    error_flag: true,
    error_category: ErrorCategory.ERAMissing,
    locked: false,
    lock_reason: "",
    correction_status: "Pending",
    resubmission_date: "",
    corrected_claim_reference: "",
    last_note: "Payment received from Cigna but missing official ERA file. Payout on hold until ERA is fetched or manually processed.",
    created_at: "2026-05-31T18:25:00Z",
    updated_at: "2026-06-14T09:00:00Z",
    updated_by: "jsmith@itera.health",
  },
  {
    claim_id: "CLM-2026-007",
    patient_id: "PAT-4402",
    patient_display_name_masked: "Tomas Ortega",
    practice_id: "PRAC_03",
    practice_name: "Summit Neurology & Wellness",
    provider_id: "PROV_04",
    provider_name: "Dr. Elena Rostova",
    provider_npi: "1827364590",
    payer_id: "PAY_02",
    payer_name: "Blue Cross Blue Shield (BCBS)",
    service_type: "RPM",
    cpt_hcpcs: "99453, 99454, 99457",
    modifiers: "",
    units: 1,
    date_of_service_from: "2026-05-15",
    date_of_service_to: "2026-05-15",
    month_of_service: "2026-05",
    billed_by: "ITERA",
    payment_received_by: "Unknown",
    claim_status: ClaimStatus.Paid,
    claim_classification: ClaimClassification.PaymentMismatch,
    billed_charge: 120.00,
    allowed_amount: 90.00,
    paid_amount: 110.00, // Paid more than allowed? Or different bank amount.
    insurance_adjustment: 10.00,
    denied_amount: 0.00,
    write_off_amount: 0.00,
    uncollectible_amount: 0.00,
    itera_direct_collection: 110.00,
    provider_direct_collection: 0.00,
    payment_to_physician: 0.00, // On hold due to mismatch
    era_received: "Yes",
    eob_received: "Yes",
    payment_date: "2026-06-11",
    check_or_eft_number: "EFT-BCBS-9128",
    carc_code: "",
    rarc_code: "",
    denial_reason: "",
    error_flag: true,
    error_category: ErrorCategory.PaymentMismatch,
    locked: true,
    lock_reason: "Claim paid amount ($110.00) exceeds expected allowed amount ($90.00). Investigate overpayment or secondary insurance.",
    correction_status: "Pending",
    resubmission_date: "",
    corrected_claim_reference: "",
    last_note: "Locked. Paid amount $110 exceeds allowed $90. Potential double coverage. Billing specialist checking.",
    created_at: "2026-05-31T18:30:00Z",
    updated_at: "2026-06-11T13:20:00Z",
    updated_by: "jsmith@itera.health",
  },
  {
    claim_id: "CLM-2026-008",
    patient_id: "PAT-5112",
    patient_display_name_masked: "Kevin Wright",
    practice_id: "PRAC_01",
    practice_name: "Metropolitan Care Group",
    provider_id: "PROV_01",
    provider_name: "Dr. Robert Chen",
    provider_npi: "1982736450",
    payer_id: "PAY_01",
    payer_name: "Medicare Texas (Novitas)",
    service_type: "CCM",
    cpt_hcpcs: "99490, 99439",
    modifiers: "95",
    units: 1,
    date_of_service_from: "2026-04-12",
    date_of_service_to: "2026-04-12",
    month_of_service: "2026-04",
    billed_by: "ITERA",
    payment_received_by: "Unknown",
    claim_status: ClaimStatus.Denied,
    claim_classification: ClaimClassification.DeniedNeedsReview,
    billed_charge: 120.00,
    allowed_amount: 0.00,
    paid_amount: 0.00,
    insurance_adjustment: 0.00,
    denied_amount: 120.00,
    write_off_amount: 0.00,
    uncollectible_amount: 0.00,
    itera_direct_collection: 0.00,
    provider_direct_collection: 0.00,
    payment_to_physician: 0.00,
    era_received: "Yes",
    eob_received: "Yes",
    payment_date: "2026-05-20",
    check_or_eft_number: "DENY-MC-441",
    carc_code: "96",
    rarc_code: "N4",
    denial_reason: "Patient not eligible on Date of Service.",
    error_flag: true,
    error_category: ErrorCategory.EligibilityIssue,
    locked: false,
    lock_reason: "",
    correction_status: "Pending",
    resubmission_date: "",
    corrected_claim_reference: "",
    last_note: "Medicare denied due to patient eligibility on DOS. Need to verify insurance active coverage and resubmit if secondary payer is active.",
    created_at: "2026-04-30T18:00:00Z",
    updated_at: "2026-05-20T10:15:00Z",
    updated_by: "jsmith@itera.health",
  },
  {
    claim_id: "CLM-2026-009",
    patient_id: "PAT-1992",
    patient_display_name_masked: "Bruno Pérez",
    practice_id: "PRAC_03",
    practice_name: "Summit Neurology & Wellness",
    provider_id: "PROV_04",
    provider_name: "Dr. Elena Rostova",
    provider_npi: "1827364590",
    payer_id: "PAY_03",
    payer_name: "Aetna Health",
    service_type: "RPM",
    cpt_hcpcs: "99454, 99457",
    modifiers: "GP",
    units: 1,
    date_of_service_from: "2026-03-01",
    date_of_service_to: "2026-03-31",
    month_of_service: "2026-03",
    billed_by: "ITERA",
    payment_received_by: "Unknown",
    claim_status: ClaimStatus.Rejected,
    claim_classification: ClaimClassification.RejectedNeedsCorrection,
    billed_charge: 150.00,
    allowed_amount: 0.00,
    paid_amount: 0.00,
    insurance_adjustment: 0.00,
    denied_amount: 150.00,
    write_off_amount: 0.00,
    uncollectible_amount: 0.00,
    itera_direct_collection: 0.00,
    provider_direct_collection: 0.00,
    payment_to_physician: 0.00,
    era_received: "No",
    eob_received: "No",
    payment_date: "",
    check_or_eft_number: "",
    carc_code: "16",
    rarc_code: "MA130",
    denial_reason: "Invalid modifier combination for RPM service.",
    error_flag: true,
    error_category: ErrorCategory.IncorrectModifier,
    locked: false,
    lock_reason: "",
    correction_status: "Pending",
    resubmission_date: "",
    corrected_claim_reference: "",
    last_note: "Payer clearinghouse rejected due to incorrect modifier GP on 99454. Needs correction to remove GP and resubmit.",
    created_at: "2026-03-31T18:00:00Z",
    updated_at: "2026-04-10T11:00:00Z",
    updated_by: "egomez@itera.health",
  },
  {
    claim_id: "CLM-2026-010",
    patient_id: "PAT-3012",
    patient_display_name_masked: "Héctor Jiménez",
    practice_id: "PRAC_01",
    practice_name: "Metropolitan Care Group",
    provider_id: "PROV_02",
    provider_name: "Dr. Sarah Jenkins",
    provider_npi: "1457382910",
    payer_id: "PAY_01",
    payer_name: "Medicare Texas (Novitas)",
    service_type: "CCM",
    cpt_hcpcs: "99490, 99439",
    modifiers: "",
    units: 1,
    date_of_service_from: "2026-05-01",
    date_of_service_to: "2026-05-31",
    month_of_service: "2026-05",
    billed_by: "ITERA",
    payment_received_by: "ITERA",
    claim_status: ClaimStatus.PartiallyPaid,
    claim_classification: ClaimClassification.Underpaid,
    billed_charge: 120.00,
    allowed_amount: 100.00,
    paid_amount: 60.00, // Coinsurance or patient responsibility unpaid yet
    insurance_adjustment: 20.00,
    denied_amount: 40.00, // Patient owes 40
    write_off_amount: 0.00,
    uncollectible_amount: 0.00,
    itera_direct_collection: 60.00,
    provider_direct_collection: 0.00,
    payment_to_physician: 42.00, // Paid 70% of 60.00
    era_received: "Yes",
    eob_received: "Yes",
    payment_date: "2026-06-10",
    check_or_eft_number: "EFT-MC-88122",
    carc_code: "2",
    rarc_code: "",
    denial_reason: "Coinsurance amount applied.",
    error_flag: false,
    error_category: "",
    locked: false,
    lock_reason: "",
    correction_status: "",
    resubmission_date: "",
    corrected_claim_reference: "",
    last_note: "Partially paid. Medicare paid 60%, 40% coinsurance billed to patient. Shared 70% of collections with Dr. Jenkins.",
    created_at: "2026-05-31T18:00:00Z",
    updated_at: "2026-06-10T09:45:00Z",
    updated_by: "egomez@itera.health",
  },
  {
    claim_id: "CLM-2026-011",
    patient_id: "PAT-9018",
    patient_display_name_masked: "Paula Torres",
    practice_id: "PRAC_01",
    practice_name: "Metropolitan Care Group",
    provider_id: "PROV_01",
    provider_name: "Dr. Robert Chen",
    provider_npi: "1982736450",
    payer_id: "PAY_04",
    payer_name: "UnitedHealthcare (UHC)",
    service_type: "RPM",
    cpt_hcpcs: "99453, 99454, 99457",
    modifiers: "",
    units: 1,
    date_of_service_from: "2026-06-01",
    date_of_service_to: "2026-06-20",
    month_of_service: "2026-06",
    billed_by: "ITERA",
    payment_received_by: "Unknown",
    claim_status: ClaimStatus.Pending,
    claim_classification: ClaimClassification.CleanClaim,
    billed_charge: 150.00,
    allowed_amount: 0.00,
    paid_amount: 0.00,
    insurance_adjustment: 0.00,
    denied_amount: 0.00,
    write_off_amount: 0.00,
    uncollectible_amount: 0.00,
    itera_direct_collection: 0.00,
    provider_direct_collection: 0.00,
    payment_to_physician: 0.00,
    era_received: "No",
    eob_received: "No",
    payment_date: "",
    check_or_eft_number: "",
    carc_code: "",
    rarc_code: "",
    denial_reason: "",
    error_flag: false,
    error_category: "",
    locked: false,
    lock_reason: "",
    correction_status: "",
    resubmission_date: "",
    corrected_claim_reference: "",
    last_note: "Submitted to UnitedHealthcare on 2026-06-21. Pending adjudication.",
    created_at: "2026-06-20T18:00:00Z",
    updated_at: "2026-06-21T08:00:00Z",
    updated_by: "egomez@itera.health",
  },
  {
    claim_id: "CLM-2026-012",
    patient_id: "PAT-0192",
    patient_display_name_masked: "Gloria Wells",
    practice_id: "PRAC_02",
    practice_name: "Vance Family Medicine",
    provider_id: "PROV_03",
    provider_name: "Dr. Marcus Vance",
    provider_npi: "1092837465",
    payer_id: "PAY_01",
    payer_name: "Medicare Texas (Novitas)",
    service_type: "CCM",
    cpt_hcpcs: "99490, 99439",
    modifiers: "",
    units: 1,
    date_of_service_from: "2026-05-15",
    date_of_service_to: "2026-05-15",
    month_of_service: "2026-05",
    billed_by: "ITERA",
    payment_received_by: "Unknown",
    claim_status: ClaimStatus.BlockedByError,
    claim_classification: ClaimClassification.BillingError,
    billed_charge: 120.00,
    allowed_amount: 0.00,
    paid_amount: 0.00,
    insurance_adjustment: 0.00,
    denied_amount: 0.00,
    write_off_amount: 0.00,
    uncollectible_amount: 0.00,
    itera_direct_collection: 0.00,
    provider_direct_collection: 0.00,
    payment_to_physician: 0.00,
    era_received: "No",
    eob_received: "No",
    payment_date: "",
    check_or_eft_number: "",
    carc_code: "",
    rarc_code: "",
    denial_reason: "",
    error_flag: true,
    error_category: ErrorCategory.MissingPatientInfo,
    locked: true,
    lock_reason: "Claim blocked due to missing Medicare Beneficiary Identifier (MBI).",
    correction_status: "Pending",
    resubmission_date: "",
    corrected_claim_reference: "",
    last_note: "Blocked in scrubbing. Missing MBI patient ID. Need practice manager to provide correct ID.",
    created_at: "2026-05-20T10:00:00Z",
    updated_at: "2026-05-22T08:30:00Z",
    updated_by: "jsmith@itera.health",
  },
  {
    claim_id: "CLM-2026-013",
    patient_id: "PAT-0044",
    patient_display_name_masked: "Miguel Ángel",
    practice_id: "PRAC_01",
    practice_name: "Metropolitan Care Group",
    provider_id: "PROV_01",
    provider_name: "Dr. Robert Chen",
    provider_npi: "1982736450",
    payer_id: "PAY_03",
    payer_name: "Aetna Health",
    service_type: "RPM",
    cpt_hcpcs: "99453, 99454, 99457",
    modifiers: "",
    units: 1,
    date_of_service_from: "2026-04-05",
    date_of_service_to: "2026-04-05",
    month_of_service: "2026-04",
    billed_by: "ITERA",
    payment_received_by: "Unknown",
    claim_status: ClaimStatus.Corrected,
    claim_classification: ClaimClassification.ReadyForResubmission,
    billed_charge: 120.00,
    allowed_amount: 0.00,
    paid_amount: 0.00,
    insurance_adjustment: 0.00,
    denied_amount: 120.00,
    write_off_amount: 0.00,
    uncollectible_amount: 0.00,
    itera_direct_collection: 0.00,
    provider_direct_collection: 0.00,
    payment_to_physician: 0.00,
    era_received: "Yes",
    eob_received: "Yes",
    payment_date: "2026-05-15",
    check_or_eft_number: "",
    carc_code: "16",
    rarc_code: "M12",
    denial_reason: "Claim missing provider NPI.",
    error_flag: false,
    error_category: "",
    locked: false,
    lock_reason: "",
    correction_status: "Ready to Rebill",
    resubmission_date: "",
    corrected_claim_reference: "CLM-2026-013-A",
    last_note: "NPI added. Claim corrected and placed in queue for resubmission.",
    created_at: "2026-04-10T09:00:00Z",
    updated_at: "2026-06-22T14:00:00Z",
    updated_by: "jsmith@itera.health",
  },
  {
    claim_id: "CLM-2026-014",
    patient_id: "PAT-0045",
    patient_display_name_masked: "Ana Gutiérrez",
    practice_id: "PRAC_01",
    practice_name: "Metropolitan Care Group",
    provider_id: "PROV_01",
    provider_name: "Dr. Robert Chen",
    provider_npi: "1982736450",
    payer_id: "PAY_03",
    payer_name: "Aetna Health",
    service_type: "RPM",
    cpt_hcpcs: "99453, 99454, 99457",
    modifiers: "",
    units: 1,
    date_of_service_from: "2026-04-05",
    date_of_service_to: "2026-04-05",
    month_of_service: "2026-04",
    billed_by: "ITERA",
    payment_received_by: "Unknown",
    claim_status: ClaimStatus.Resubmitted,
    claim_classification: ClaimClassification.CleanClaim,
    billed_charge: 120.00,
    allowed_amount: 0.00,
    paid_amount: 0.00,
    insurance_adjustment: 0.00,
    denied_amount: 0.00,
    write_off_amount: 0.00,
    uncollectible_amount: 0.00,
    itera_direct_collection: 0.00,
    provider_direct_collection: 0.00,
    payment_to_physician: 0.00,
    era_received: "No",
    eob_received: "No",
    payment_date: "",
    check_or_eft_number: "",
    carc_code: "",
    rarc_code: "",
    denial_reason: "",
    error_flag: false,
    error_category: "",
    locked: false,
    lock_reason: "",
    correction_status: "Resubmitted",
    resubmission_date: "2026-06-23",
    corrected_claim_reference: "CLM-2026-013",
    last_note: "Rebilled to Aetna on 2026-06-23 with correct billing NPI. Referencing original CLM-2026-013.",
    created_at: "2026-06-23T08:00:00Z",
    updated_at: "2026-06-23T11:00:00Z",
    updated_by: "egomez@itera.health",
  },
  {
    claim_id: "CLM-2026-015",
    patient_id: "PAT-4091",
    patient_display_name_masked: "Karla Flores",
    practice_id: "PRAC_02",
    practice_name: "Vance Family Medicine",
    provider_id: "PROV_03",
    provider_name: "Dr. Marcus Vance",
    provider_npi: "1092837465",
    payer_id: "PAY_02",
    payer_name: "Blue Cross Blue Shield (BCBS)",
    service_type: "RPM",
    cpt_hcpcs: "99454, 99457, 99458",
    modifiers: "",
    units: 1,
    date_of_service_from: "2026-02-10",
    date_of_service_to: "2026-03-10",
    month_of_service: "2026-02",
    billed_by: "ITERA",
    payment_received_by: "Unknown",
    claim_status: ClaimStatus.WrittenOff,
    claim_classification: ClaimClassification.WriteOffCandidate,
    billed_charge: 150.00,
    allowed_amount: 0.00,
    paid_amount: 0.00,
    insurance_adjustment: 0.00,
    denied_amount: 150.00,
    write_off_amount: 150.00,
    uncollectible_amount: 150.00,
    itera_direct_collection: 0.00,
    provider_direct_collection: 0.00,
    payment_to_physician: 0.00,
    era_received: "Yes",
    eob_received: "Yes",
    payment_date: "2026-03-15",
    check_or_eft_number: "",
    carc_code: "29",
    rarc_code: "",
    denial_reason: "Timely filing limit expired.",
    error_flag: false,
    error_category: "",
    locked: false,
    lock_reason: "",
    correction_status: "",
    resubmission_date: "",
    corrected_claim_reference: "",
    last_note: "Written off due to timely filing limit expired. Provider failed to send logs to ITERA within 60 days.",
    created_at: "2026-02-15T10:00:00Z",
    updated_at: "2026-06-20T11:00:00Z",
    updated_by: "egomez@itera.health",
  },
];

// Pre-calculate seed claims
export const SEED_CLAIMS: Claim[] = rawClaims.map(c => calculateClaimFinancials(c));

export const SEED_PAYMENTS: Payment[] = [
  {
    payment_id: "PAY-RECON-001",
    claim_id: "CLM-2026-001",
    payment_date: "2026-06-12",
    payment_received_by: "ITERA",
    payer_name: "Medicare Texas (Novitas)",
    amount: 110.00,
    check_or_eft_number: "EFT-881273",
    era_id: "ERA-9912",
    eob_id: "EOB-9912",
    payment_source: "ERA",
    notes: "Auto-matched payment from Medicare Novitas.",
    created_at: "2026-06-12T14:30:00Z",
    updated_at: "2026-06-12T14:30:00Z",
  },
  {
    payment_id: "PAY-RECON-002",
    claim_id: "CLM-2026-002",
    payment_date: "2026-06-15",
    payment_received_by: "Provider",
    payer_name: "Blue Cross Blue Shield (BCBS)",
    amount: 90.00,
    check_or_eft_number: "CHK-992182",
    era_id: "ERA-3312",
    eob_id: "EOB-3312",
    payment_source: "Manual",
    notes: "Provider confirmed check deposit in local bank.",
    created_at: "2026-06-15T16:10:00Z",
    updated_at: "2026-06-15T16:10:00Z",
  },
  {
    payment_id: "PAY-RECON-003",
    claim_id: "CLM-2026-003",
    payment_date: "2026-06-10",
    payment_received_by: "Provider",
    payer_name: "Aetna Health",
    amount: 100.00,
    check_or_eft_number: "EFT-AE7721",
    era_id: "ERA-A11",
    eob_id: "EOB-A11",
    payment_source: "Manual",
    notes: "Reported in weekly billing export from Dr. Vance's staff.",
    created_at: "2026-06-10T11:00:00Z",
    updated_at: "2026-06-10T11:00:00Z",
  }
];

export const SEED_NOTES: Note[] = [
  {
    note_id: "NTE-001",
    claim_id: "CLM-2026-012",
    note_type: "Billing",
    note_text: "Contacted Dr. Vance's practice manager Sarah to ask for patient Gerald Wright's Medicare Beneficiary Identifier (MBI). Waiting on response.",
    created_by: "jsmith@itera.health",
    created_at: "2026-05-22T08:30:00Z",
  },
  {
    note_id: "NTE-002",
    claim_id: "CLM-2026-007",
    note_type: "Reconciliation",
    note_text: "Claim paid amount ($110) exceeds expected allowed amount ($90). We need to double check if Aetna has paid a secondary portion or if there was a billing calculation error.",
    created_by: "jsmith@itera.health",
    created_at: "2026-06-11T13:20:00Z",
  },
  {
    note_id: "NTE-003",
    claim_id: "CLM-2026-013",
    note_type: "Correction",
    note_text: "Corrected the NPI in the claim master record. System shows status is corrected and queued for rebill.",
    created_by: "jsmith@itera.health",
    created_at: "2026-06-22T14:00:00Z",
  }
];

export const SEED_AUDIT_LOGS: AuditLog[] = [
  {
    audit_id: "AUD-001",
    claim_id: "CLM-2026-012",
    action_type: "Lock",
    field_name: "locked",
    previous_value: "false",
    new_value: "true",
    reason: "Claim blocked due to missing Medicare Beneficiary Identifier (MBI).",
    changed_by: "jsmith@itera.health",
    changed_at: "2026-05-22T08:30:00Z",
  },
  {
    audit_id: "AUD-002",
    claim_id: "CLM-2026-007",
    action_type: "Lock",
    field_name: "locked",
    previous_value: "false",
    new_value: "true",
    reason: "Claim paid amount exceeds allowed amount. Put on reconciliation hold.",
    changed_by: "jsmith@itera.health",
    changed_at: "2026-06-11T13:20:00Z",
  },
  {
    audit_id: "AUD-003",
    claim_id: "CLM-2026-013",
    action_type: "Status Change",
    field_name: "claim_status",
    previous_value: "Denied",
    new_value: "Corrected",
    reason: "NPI mismatch resolved by billing manager.",
    changed_by: "jsmith@itera.health",
    changed_at: "2026-06-22T14:00:00Z",
  }
];
